# Generated by Django 4.0.3 on 2022-04-03 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('all_abs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='biology',
            name='title',
            field=models.CharField(default=1, max_length=2),
            preserve_default=False,
        ),
    ]
