# Generated by Django 4.0.3 on 2022-04-04 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('all_abs', '0003_chemistry_title_english_title_history_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='obz',
            name='image',
            field=models.ImageField(upload_to='all_abs/obz/'),
        ),
        migrations.AlterField(
            model_name='oid',
            name='image',
            field=models.ImageField(upload_to='all_abs/oid/'),
        ),
    ]
