# Generated by Django 4.0.5 on 2022-06-26 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('all_abs', '0004_alter_obz_image_alter_oid_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='english',
            name='title',
        ),
    ]
