# Generated by Django 4.0.5 on 2022-06-26 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('all_abs', '0005_remove_english_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='biology',
            name='title',
        ),
        migrations.RemoveField(
            model_name='chemistry',
            name='title',
        ),
        migrations.RemoveField(
            model_name='history',
            name='title',
        ),
        migrations.RemoveField(
            model_name='information',
            name='title',
        ),
        migrations.RemoveField(
            model_name='literature',
            name='title',
        ),
        migrations.RemoveField(
            model_name='math',
            name='title',
        ),
        migrations.RemoveField(
            model_name='obz',
            name='title',
        ),
        migrations.RemoveField(
            model_name='oid',
            name='title',
        ),
        migrations.RemoveField(
            model_name='physics',
            name='title',
        ),
        migrations.RemoveField(
            model_name='russian_language',
            name='title',
        ),
        migrations.RemoveField(
            model_name='social_studies',
            name='title',
        ),
    ]
